# Generated by Django 5.0.1 on 2024-01-23 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="Title"),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "published_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=127
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_date",),
            },
        ),
    ]
